/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ORG_ECLIPSE_TAHU_PROTOBUF_SPARKPLUG_B_PB_H_INCLUDED
#define PB_ORG_ECLIPSE_TAHU_PROTOBUF_SPARKPLUG_B_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _org_eclipse_tahu_protobuf_Payload {
    bool has_timestamp;
    uint64_t timestamp;
    pb_callback_t metrics;
    bool has_seq;
    uint64_t seq;
} org_eclipse_tahu_protobuf_Payload;

typedef struct _org_eclipse_tahu_protobuf_Payload_Metric {
    bool has_name;
    char name[24];
    bool has_alias;
    uint64_t alias;
    bool has_timestamp;
    uint64_t timestamp;
    bool has_datatype;
    uint32_t datatype;
    bool has_is_historical;
    bool is_historical;
    bool has_is_transient;
    bool is_transient;
    bool has_is_null;
    bool is_null;
    pb_size_t which_value;
    union _org_eclipse_tahu_protobuf_Payload_Metric_value {
        uint32_t int_value;
        uint64_t long_value;
        float float_value;
        double double_value;
        bool boolean_value;
    } value;
} org_eclipse_tahu_protobuf_Payload_Metric;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define org_eclipse_tahu_protobuf_Payload_init_default {false, 0, {{NULL}, NULL}, false, 0}
#define org_eclipse_tahu_protobuf_Payload_Metric_init_default {false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0}}
#define org_eclipse_tahu_protobuf_Payload_init_zero {false, 0, {{NULL}, NULL}, false, 0}
#define org_eclipse_tahu_protobuf_Payload_Metric_init_zero {false, "", false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define org_eclipse_tahu_protobuf_Payload_timestamp_tag 1
#define org_eclipse_tahu_protobuf_Payload_metrics_tag 2
#define org_eclipse_tahu_protobuf_Payload_seq_tag 3
#define org_eclipse_tahu_protobuf_Payload_Metric_name_tag 1
#define org_eclipse_tahu_protobuf_Payload_Metric_alias_tag 2
#define org_eclipse_tahu_protobuf_Payload_Metric_timestamp_tag 3
#define org_eclipse_tahu_protobuf_Payload_Metric_datatype_tag 4
#define org_eclipse_tahu_protobuf_Payload_Metric_is_historical_tag 5
#define org_eclipse_tahu_protobuf_Payload_Metric_is_transient_tag 6
#define org_eclipse_tahu_protobuf_Payload_Metric_is_null_tag 7
#define org_eclipse_tahu_protobuf_Payload_Metric_int_value_tag 10
#define org_eclipse_tahu_protobuf_Payload_Metric_long_value_tag 11
#define org_eclipse_tahu_protobuf_Payload_Metric_float_value_tag 12
#define org_eclipse_tahu_protobuf_Payload_Metric_double_value_tag 13
#define org_eclipse_tahu_protobuf_Payload_Metric_boolean_value_tag 14

/* Struct field encoding specification for nanopb */
#define org_eclipse_tahu_protobuf_Payload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, CALLBACK, REPEATED, MESSAGE,  metrics,           2) \
X(a, STATIC,   OPTIONAL, UINT64,   seq,               3)
#define org_eclipse_tahu_protobuf_Payload_CALLBACK pb_default_field_callback
#define org_eclipse_tahu_protobuf_Payload_DEFAULT NULL
#define org_eclipse_tahu_protobuf_Payload_metrics_MSGTYPE org_eclipse_tahu_protobuf_Payload_Metric

#define org_eclipse_tahu_protobuf_Payload_Metric_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, UINT64,   alias,             2) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   datatype,          4) \
X(a, STATIC,   OPTIONAL, BOOL,     is_historical,     5) \
X(a, STATIC,   OPTIONAL, BOOL,     is_transient,      6) \
X(a, STATIC,   OPTIONAL, BOOL,     is_null,           7) \
X(a, STATIC,   ONEOF,    UINT32,   (value,int_value,value.int_value),  10) \
X(a, STATIC,   ONEOF,    UINT64,   (value,long_value,value.long_value),  11) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),  12) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),  13) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean_value,value.boolean_value),  14)
#define org_eclipse_tahu_protobuf_Payload_Metric_CALLBACK NULL
#define org_eclipse_tahu_protobuf_Payload_Metric_DEFAULT NULL

extern const pb_msgdesc_t org_eclipse_tahu_protobuf_Payload_msg;
extern const pb_msgdesc_t org_eclipse_tahu_protobuf_Payload_Metric_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define org_eclipse_tahu_protobuf_Payload_fields &org_eclipse_tahu_protobuf_Payload_msg
#define org_eclipse_tahu_protobuf_Payload_Metric_fields &org_eclipse_tahu_protobuf_Payload_Metric_msg

/* Maximum encoded size of messages (where known) */
/* org_eclipse_tahu_protobuf_Payload_size depends on runtime parameters */
#define ORG_ECLIPSE_TAHU_PROTOBUF_SPARKPLUG_B_PB_H_MAX_SIZE org_eclipse_tahu_protobuf_Payload_Metric_size
#define org_eclipse_tahu_protobuf_Payload_Metric_size 70

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
